version: '3.3'
services:
    db:
        container_name: hello-meals-db
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: hellomeals
        ports:
            - "5482:5432"
    hello-meals:
        container_name: hello-meals-prod
        environment:
            - USERNAME=${USERNAME}
            - PASSWORD=${PASSWORD}
            - EMAIL=${EMAIL}
            - DEBUG=False
            - APP_URL=${APP_URL}
            - TIMEZONE=${TIMEZONE}
            - COUNTRY=${COUNTRY}
            - POSTGRES_HOST=db
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - DOWNLOAD_IMAGES=${DOWNLOAD_IMAGES} #Should images get downloaded or use HelloFresh urls (True/False)
        ports:
            - '6753:6753'
        image: 'hellomeals:localdev'
        volumes:
            - ./data:/HelloMeals/src/data