# Generated by Django 4.2.1 on 2023-05-21 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
                ('cardLink', models.CharField(max_length=2000)),
                ('websiteLink', models.CharField(max_length=2000)),
                ('prepTime', models.DurationField()),
                ('totalTime', models.DurationField()),
                ('difficulty', models.IntegerField()),
                ('createdAt', models.DateTimeField()),
                ('favoritesCount', models.IntegerField()),
                ('averageRating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ratingCount', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/recipes')),
                ('ingredients', models.ManyToManyField(to='MealManager.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=7)),
                ('unit', models.CharField(max_length=255)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealManager.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealManager.recipe')),
            ],
        ),
    ]
