# Generated by Django 4.2.1 on 2023-05-21 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0002_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('helloFreshId', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('energyKj', models.IntegerField()),
                ('energyKcal', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('fatSaturated', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('salt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('helloFreshId', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('helloFreshId', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='helloFreshId',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='helloFreshId',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='updatedAt',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorkSteps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/workSteps')),
                ('relatedRecipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealManager.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeUtensil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealManager.recipe')),
                ('utensil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealManager.utensil')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealManager.recipe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealManager.tag')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCuisine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealManager.cuisine')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealManager.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrients',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MealManager.nutrients'),
            preserve_default=False,
        ),
    ]
