# Generated by Django 4.2.1 on 2023-05-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0003_cuisine_nutrients_tag_utensil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuisine',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.RemoveField(
            model_name='utensil',
            name='id',
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='helloFreshId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='helloFreshId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='helloFreshId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='helloFreshId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utensil',
            name='helloFreshId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
