# Generated by Django 4.2.1 on 2023-05-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0006_alter_recipe_description_alter_recipe_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='helloFreshId',
            field=models.TextField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='helloFreshId',
            field=models.TextField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='helloFreshId',
            field=models.TextField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='helloFreshId',
            field=models.TextField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='utensil',
            name='helloFreshId',
            field=models.TextField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
