# Generated by Django 4.2.1 on 2023-05-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0007_alter_cuisine_hellofreshid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='images/recipes'),
        ),
    ]
