# Generated by Django 4.2.1 on 2023-05-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0008_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecuisine',
            name='id',
            field=models.TextField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='id',
            field=models.TextField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='recipetag',
            name='id',
            field=models.TextField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='recipeutensil',
            name='id',
            field=models.TextField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='worksteps',
            name='id',
            field=models.TextField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
