# Generated by Django 4.2.1 on 2023-05-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0009_alter_recipecuisine_id_alter_recipeingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
