# Generated by Django 4.2.1 on 2023-05-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0010_alter_recipeingredient_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrients',
            name='id',
            field=models.TextField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
