# Generated by Django 4.2.1 on 2023-05-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0011_alter_nutrients_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='HelloFreshImageUrl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='HelloFreshImageUrl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worksteps',
            name='HelloFreshImageUrl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
