# Generated by Django 4.2.1 on 2023-05-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0013_alter_utensil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='helloFreshActive',
            field=models.BooleanField(default=True),
        ),
    ]
