# Generated by Django 4.2.1 on 2023-05-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0014_recipe_hellofreshactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
