# Generated by Django 4.2.1 on 2023-05-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0015_alter_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksteps',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
