# Generated by Django 4.2.1 on 2023-05-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0016_alter_worksteps_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='highlighted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='isAddon',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='isComplete',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='isDinnerToLunch',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='isExcludedFromIndex',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='isPremium',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
