# Generated by Django 4.2.1 on 2023-05-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0018_category_recipe_clonedfrom_recipe_videolink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='clonedFrom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
