# Generated by Django 4.2.1 on 2023-05-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0018_category_recipe_clonedfrom_recipe_videolink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='helloFreshActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
