# Generated by Django 4.2.1 on 2023-05-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0019_alter_recipe_hellofreshactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.IntegerField(default=1),
        ),
    ]
