# Generated by Django 4.2.1 on 2023-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0021_alter_nutrients_carbs_alter_nutrients_energykcal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='isPlus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='viewCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
