# Generated by Django 4.2.1 on 2023-05-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0023_taggroup_tag_taggroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecuisine',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='recipecuisine',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Cuisine',
        ),
        migrations.DeleteModel(
            name='RecipeCuisine',
        ),
    ]
