# Generated by Django 4.2.1 on 2023-05-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0025_tagmerge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmerge',
            name='target',
            field=models.CharField(max_length=255),
        ),
    ]
