# Generated by Django 4.2.1 on 2023-05-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0027_alter_recipetag_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmerge',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
