# Generated by Django 4.2.1 on 2023-05-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0028_tagmerge_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmerge',
            name='target',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
