# Generated by Django 4.2.1 on 2023-06-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0030_add_similarity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipetag',
            unique_together=set(),
        ),
    ]
