# Generated by Django 4.2.1 on 2023-06-06 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0031_alter_recipetag_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientGroup',
            fields=[
                ('id', models.TextField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_groups',
            field=models.ManyToManyField(to='MealManager.ingredientgroup'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='ingredient_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MealManager.ingredientgroup'),
            preserve_default=False,
        ),
    ]
