# Generated by Django 4.2.1 on 2023-06-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0033_alter_ingredientgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='healthScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
