# Generated by Django 4.2.1 on 2023-06-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0037_recipe_favoriteby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
