# Generated by Django 4.2.1 on 2023-06-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0044_stock_shoppinglist_profile_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='MealManager.ingredient'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='MealManager.ingredient'),
        ),
    ]
