# Generated by Django 4.2.1 on 2023-06-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MealManager', '0044_remove_stock_owner_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='Stock default name', max_length=255),
            preserve_default=False,
        ),
    ]
