# Generated by Django 4.2.1 on 2023-06-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0047_remap_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_groups',
        ),
    ]
