# Generated by Django 4.2.1 on 2023-06-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('MealManager', '0051_recipestockingredientcount'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipestockingredientcount',
            constraint=models.UniqueConstraint(fields=('recipe', 'stock'), name='recipe_stock_primary_key'),
        ),
    ]
