# Generated by Django 4.2.5 on 2026-08-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0052_recipestockingredientcount_recipe_stock_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.IntegerField(choices=[(1, 'HelloFresh'), (2, 'KitchenStories'), (3, 'Chefkoch'), (4, 'Lecker'), (5, 'EatSmarter'), (6, 'Yazio'), (7, 'Mob')], default=1),
        ),
    ]
