# Generated by Django 4.2.5 on 2026-08-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealManager', '0053_alter_recipe_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stock',
        ),
        migrations.DeleteModel(
            name='RecipeStockIngredientCount',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
