name: Docker build and deploy image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags:
            bastianlo/hellomeals:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }}
      - name: Tag with version
        run: |
          echo "Tagging image with version: ${{ steps.docker_build.outputs.digest }}"
          docker tag bastianlo/hellomeals:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }} bastianlo/hellomeals:${{ github.run_id }}
          docker push bastianlo/hellomeals:${{ github.run_id }}
